name=ESP_TelnetServer
version=1.0.0
author=Muhammad Brilian Erranaomi <brilianeranaomi@gmail.com>
maintainer=Muhammad Brilian Erranaomi <brilianeranaomi@gmail.com>
sentence=Telnet server with wifi and ethernet for ESP32
paragraph=Telnet server with wifi and ethernet for ESP32
category=Timing
url=https://github.com/brili99/ESP_TelnetServer
architectures=esp32
depends=Ethernet